version: '3.8'

services:
  app:
    build:
      context: ./spring-petclinic
    image: localhost:5000/petclinic:latest
    ports:
      - "8088:8080" 
    environment:
      - SERVER_PORT=8080
      - management.endpoints.web.exposure.include=health,info,prometheus
    depends_on:
      - db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge